openapi: '3.0.2'

info:
  title: OnBoarding API
  description: STD22076
  version: '1.0'
  
servers:
  - url: https://STD22076.com

paths:
  /Students:
    get:
      tags:
        - Students

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Students'
                      
        '500':
          description: Internal server error 


    post:
      tags:
        - Students
      summary: Create new Student 
      requestBody:
          required: true
          content:
            'application/x-www-form-urlencoded':
              schema:
                $ref: '#/components/schemas/Students'
      responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Students'
          '500':
            description: Internal server error


    put:
      tags:
        - Students
      summary: Update an existing Students
      parameters:
        - name: id
          in: query
          description: id to update
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          'application/x-www-form-urlencoded':
            schema:
              $ref: '#/components/schemas/Students'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Students'
        '400':
          description: Invalid ID supplied
        '500':
          description: Internal server error


    delete:
      tags:
        - Students
      summary: Deletes A student
      parameters:
        - name: id
          in: query
          description: ID to delete
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK


  /Teachers:       
    get:
      tags:
        - Teachers    
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teachers'
        '500':
          description: Internal server error

    post:
      tags:
        - Teachers
      summary: Create new Teachers
      requestBody:
          required: true
          content:
            'application/x-www-form-urlencoded':
              schema:
                $ref: '#/components/schemas/Teachers'
      responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Teachers'
          '500':
            description: Internal server error

components:
  schemas:
    Students:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 76
        name:
          type: string
          example: Tendry
        birthdate:
          type: string
          format: date
          example: 2004-05-26

    Teachers:
      type: object
      properties:
        name:
          type: string
          example: Ramarozaka
        first_name:
          type: string
          example: Toky
        course:
          items:
            type: object      
            properties:
              course_name:    
                type: string
              code:    
                type: string
              duration: 
                type: string
          example:
            - course_name: Algorithmique
              course_code: PROG1
              course_duration: 3 months
            - course_name: Interface Design
              course_code: WEB1
              course_duration: 2 months
            - course_name: Persistance de données
              course_code: Donnée1
              course_duration: 5 months

          
        

  



        

